# Generated by Django 4.1.5 on 2023-01-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('applicationId', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('application_name', models.CharField(max_length=50)),
                ('application_url', models.CharField(max_length=200)),
                ('application_logo', models.ImageField(upload_to='')),
            ],
        ),
    ]
