# Generated by Django 4.1.5 on 2023-01-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.BigIntegerField()),
                ('application_name', models.CharField(max_length=50)),
                ('application_url', models.CharField(max_length=200)),
                ('application_logo', models.CharField(max_length=200)),
            ],
        ),
    ]
