# Generated by Django 4.1.5 on 2023-01-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageApplications', '0002_alter_app_applicationid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='application_logo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
