# Generated by Django 4.1.5 on 2023-01-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageApplications', '0003_alter_app_application_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='application_logo',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
