# Generated by Django 4.1.5 on 2023-01-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageApplications', '0004_alter_app_application_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='applicationId',
            new_name='application_Id',
        ),
        migrations.RenameField(
            model_name='app',
            old_name='application_url',
            new_name='application_path',
        ),
        migrations.AlterField(
            model_name='app',
            name='application_logo',
            field=models.ImageField(upload_to='static/media/images/'),
        ),
    ]
